Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	annotate
	3	bwa_map
	1	samtools_merge_bam
	1	samtools_rmdup
	3	samtools_sort_bam
	1	snp_indel_calling
	11

Job 10: ############ start bwa mapping ####################
Reason: Missing output files: mappingKPGP-00001/KPGP-00001_L3.bam

bwa mem -t 1 -M /DataBase/Human/hg19/refgenome/hg19.fa rawdata/KPGP-00001/KPGP-00001_L3_R1.fq rawdata/KPGP-00001/KPGP-00001_L3_R2.fq | samtools -b -S -t /DataBase/Human/hg19/refgenome/hg19.fa.fai > mappingKPGP-00001/KPGP-00001_L3.bam 2>log/KPGP-00001_bwa_map.log
Error in rule bwa_map:
    jobid: 10
    output: mappingKPGP-00001/KPGP-00001_L3.bam
    log: log/KPGP-00001_bwa_map.log

RuleException:
CalledProcessError in line 36 of /home/sxuan/mypipe/example/wgs.py:
Command ' set -euo pipefail;  bwa mem -t 1 -M /DataBase/Human/hg19/refgenome/hg19.fa rawdata/KPGP-00001/KPGP-00001_L3_R1.fq rawdata/KPGP-00001/KPGP-00001_L3_R2.fq | samtools -b -S -t /DataBase/Human/hg19/refgenome/hg19.fa.fai > mappingKPGP-00001/KPGP-00001_L3.bam 2>log/KPGP-00001_bwa_map.log ' returned non-zero exit status 1.
  File "/home/sxuan/mypipe/example/wgs.py", line 36, in __rule_bwa_map
  File "/opt/anaconda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job bwa_map since they might be corrupted:
mappingKPGP-00001/KPGP-00001_L3.bam
Will exit after finishing currently running jobs.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/sxuan/mypipe/example/.snakemake/log/2018-02-03T150401.913778.snakemake.log
